---
# GCP Admin service account secret - used by GCP ProviderConfig
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: gcp-creds
type: Opaque
data:
  credentials.json: 
---
# GCP ProviderConfig with service account secret reference
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-conf
spec:
  projectID: 
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: credentials.json
