---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: sample-cluster
  labels:
    example: "true"
spec:
  forProvider:
    region: eu-central-1
    # Defined in examples/iam
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
    version: "1.21"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: default
  providerConfigRef:
    name: aws-conf
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: my-group
  labels:
    example: "true"
spec:
  forProvider:
    region: eu-central-1
    clusterNameRef:
      name: sample-cluster
    scalingConfig:
      desiredSize: 1
      maxSize: 1
      minSize: 1 
  providerConfigRef:
    name: aws-conf
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Addon
metadata:
  name: sample-addon
  labels:
    example: "true"
spec:
  forProvider:
    region: eu-central-1
    addonName: coredns
    addonVersion: "v1.8.4-eksbuild.1"
    clusterNameRef:
      name: sample-cluster
  providerConfigRef:
    name: aws-conf
