---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: dev-cluster
  labels:
    env: "dev"
spec:
  forProvider:
    region: eu-central-1
    roleArnRef:
      name: eksrole
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      subnetIds:
        - ""
    version: "1.21"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: default
  providerConfigRef:
    name: aws-conf
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: eks-node-group
  labels:
    env: "dev"
spec:
  forProvider:
    region: eu-central-1
    clusterNameRef:
      name: dev-cluster
    nodeRoleRef:
      name: eksnoderole  
    subnets:
      - ""
    scalingConfig:
      desiredSize: 1
      maxSize: 1
      minSize: 1 
  providerConfigRef:
    name: aws-conf
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Addon
metadata:
  name: eks-addon
  labels:
    env: "dev"
spec:
  forProvider:
    region: eu-central-1
    addonName: coredns
    addonVersion: "v1.8.4-eksbuild.1"
    clusterNameRef:
      name: dev-cluster
  providerConfigRef:
    name: aws-conf
