---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sample
  namespace: fleet-local
spec:
  repo: "https://github.com/encodeflush/fleet-crossplane"
  paths:
  - providers/gcp/container
