apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: k8s-dev
spec:
  forProvider:
    initialClusterVersion: "1.21.5-gke.1302"
    location: europe-west1
    #serviceAccount: sa-test
    networkConfig:
      enableIntraNodeVisibility: true
      datapathProvider: "ADVANCED_DATAPATH"
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    addonsConfig:
      gcePersistentDiskCsiDriverConfig:
        enabled: true
    network: "default"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: gke-conn
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: crossplane-np
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 5
      minNodeCount: 3  
    clusterRef:
      name: k8s-dev
    config:
      machineType: n1-standard-1
      sandboxConfig:
        type: gvisor
      diskSizeGb: 80
      diskType: pd-ssd
      imageType: cos_containerd
      labels:
        env: dev
      oauthScopes:
      - "https://www.googleapis.com/auth/devstorage.read_only"
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/servicecontrol"
      - "https://www.googleapis.com/auth/service.management.readonly"
      - "https://www.googleapis.com/auth/trace.append"      
    initialNodeCount: 3
    locations:
      - "europe-west1-b"
